swagger: "2.0"
info:
  title: FX Market Price API
  description: This API allow you to check the lastest market prices in FX Market. Offered by Santander Corporate & Investment Banking (FX)
  version: 1.0.0
host: api.example.com
basePath: /dev/v1
schemes:
  - https
paths:

  /prices/latest:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      parameters:
      - in: query
        name: currency
        required: true
        type: string
        enum: ['EUR/USD', 'GBP/USD', 'EUR/JPY']
        description: The currency you want to check
      produces:
        - application/json
      responses:
        200:
          description: Return an object with the last price of currency
          schema:
            $ref: '#/definitions/LastPrice'
            
        400:
          description: Bad Request
        422:
          description: Unprocessable Entity. Check request parameters.
          
definitions:
  LastPrice:
    type: object
    properties:
      currency:
        type: string
        description: The currency identifier.
      price:
        type: number
        description: The last price of currency change